work_dir: ./work_dir/nucla/resnet_only

feeder: feeder.feeder_nucla_resnet.Feeder
train_feeder_args:
  rgb_path: /path/to/your/st-roi-train-image
  label_path: train
  random_flip: True
  temporal_rgb_frames: 5

test_feeder_args:
  rgb_path: /path/to/your/st-roi-test-image
  label_path: val
  temporal_rgb_frames: 5

model: models.resnet_only.Model
model_args:
  num_class: 10
  pretrained: True

# Training
device: [0]
batch_size: 32
test_batch_size: 32
base_lr: 0.01
step: [20, 40]
num_epoch: 50
eval_interval: 1